services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Change host port to 5001
    environment:
      DB_NAME: upload_db
      DB_USER: root
      DB_PASSWORD: ''
      DB_HOST: mysql
      DB_DIALECT: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"  # Change host port to 3307
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: upload_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql

volumes:
  mysql-data:
